from pathlib import Path
import yaml, json
root=Path('/root/sikk-gmgn')
s00=root/'system/unified_standardization'
now='2026-05-14T12:50:47Z'
version='0.1.0'
status='active_with_gaps'
files_by_dir={
'00_module_charter':['s00_unified_standardization_charter.md','s00_scope_boundary.yaml','s00_standard_object_registry.yaml'],
'01_global_identity':['global_id_standard.yaml','global_status_code_table.yaml','global_event_type_registry.yaml'],
'02_goal_mapping':['system_goal_mapping.yaml','token_judgment_goal_map.yaml','phase_goal_alignment_matrix.yaml','goal_to_runner_consumption_map.yaml'],
'03_method_wheel_mapping':['method_wheel_registry.yaml','method_to_phase_map.yaml','method_to_field_map.yaml','method_to_decision_map.yaml','method_to_counter_evidence_map.yaml'],
'04_domain_entity_model':['canonical_entity_model.yaml','token_entity_schema.yaml','wallet_entity_schema.yaml','cluster_entity_schema.yaml','trade_event_schema.yaml','signal_entity_schema.yaml','decision_entity_schema.yaml','paper_position_entity_schema.yaml'],
'05_data_lineage':['data_source_registry.yaml','field_lineage_registry.yaml','file_lineage_map.yaml','decision_lineage_map.yaml','report_lineage_map.yaml'],
'06_field_governance':['field_permission_matrix.yaml','field_mutation_policy.yaml','field_confidence_policy.yaml','field_manual_override_policy.yaml'],
'07_schema_contract':['schema_index.yaml','contract_index.yaml','phase_input_contracts.yaml','phase_output_contracts.yaml','handoff_contracts.yaml','report_contracts.yaml','backward_compatibility_policy.yaml'],
'08_runner_binding':['runner_registry.yaml','phase_runner_binding.yaml','validation_runner_registry.yaml','replay_runner_registry.yaml','paper_runner_binding.yaml','runner_failure_policy.yaml','runner_output_contract_map.yaml'],
'09_trace_acceptance_handoff':['trace_event_schema.yaml','process_trace_policy.yaml','acceptance_gate_matrix.yaml','acceptance_evidence_schema.yaml','handoff_packet_standard.yaml','downstream_consumption_matrix.yaml'],
'10_validation_r00':['r00_validation_controller.md','r00_validation_checklist.yaml','r00_runner_dry_run_matrix.yaml','r00_replay_validation_matrix.yaml','r00_failure_report_schema.yaml'],
'11_permission_gate_p08':['p08_permission_gate_policy.yaml','p08_action_permission_matrix.yaml','p08_paper_only_boundary.yaml','p08_real_trade_forbidden_policy.yaml','p08_risk_event_schema.yaml'],
'12_review_upgrade_p09_p10':['p09_review_case_schema.yaml','p09_failure_attribution_schema.yaml','p09_replay_packet_schema.yaml','p10_upgrade_candidate_schema.yaml','p10_shadow_validation_policy.yaml','p10_rule_promotion_policy.yaml'],
'13_issue_task_registry':['issue_registry.yaml','issue_taxonomy.yaml','task_packet_schema.yaml','task_priority_policy.yaml','task_acceptance_policy.yaml'],
'14_legacy_absorption':['legacy_asset_inventory.yaml','legacy_to_new_mapping.yaml','legacy_runtime_absorption_plan.yaml','legacy_keep_deprecate_migrate_policy.yaml','legacy_readonly_boundary.yaml'],
'15_sample_regression_rollback':['sample_library_index.yaml','labeled_token_case_schema.yaml','regression_suite_registry.yaml','regression_result_schema.yaml','rollback_policy.yaml','rule_version_registry.yaml'],
'16_security_boundary':['security_boundary_policy.yaml','paper_only_execution_policy.yaml','real_trade_forbidden_policy.yaml','api_key_permission_policy.yaml','manual_confirmation_policy.yaml','emergency_stop_policy.yaml'],
'index':['unified_standardization_index.yaml','phase_consumption_matrix.yaml','file_to_runner_index.yaml','runner_to_phase_index.yaml','schema_to_contract_index.yaml','goal_to_phase_to_runner_index.yaml','report_to_lineage_index.yaml']}
for d in files_by_dir: (s00/d).mkdir(parents=True, exist_ok=True)
def meta(file_id, producer='S00_unified_system_standardization', consumer=None, acceptance=None):
    return {'meta':{'standard_id':file_id,'producer':producer,'consumer':consumer or ['HER Control Plane','Phase Controllers','R00 validation controller'],'version':version,'status':status,'created_at':now,'acceptance':acceptance or 'Must parse and be listed in unified_standardization_index; runtime binding may remain WITH_GAPS.'}}
def dump(rel, obj):
    p=s00/rel; p.parent.mkdir(parents=True, exist_ok=True); p.write_text(yaml.safe_dump(obj, allow_unicode=True, sort_keys=False), encoding='utf-8')
def md(rel, text):
    p=s00/rel; p.parent.mkdir(parents=True, exist_ok=True); p.write_text(text, encoding='utf-8')
md('00_module_charter/s00_unified_standardization_charter.md', f'''# S00_unified_system_standardization Charter

- producer: S00_unified_system_standardization
- consumer: HER / SIKK Control Plane, K00/P00/R00/P01-P10, paper runtime, P09/P10 review-upgrade
- version: {version}
- status: {status}
- acceptance: every judgment must trace goal → method → data → field lineage → schema/contract → runner → trace → acceptance → handoff → P08 → paper-only → P09/P10 → regression/rollback.

## Role
S00 is the unified standard control layer for HER / SIKK. It is not a document pile and not an extra trading phase.

## Hard boundaries
- No real swap.
- No private key read/write/storage.
- No signing or broadcast.
- Paper-only actions require P08 permission gate.
- P09/P10 review upgrades cannot mutate runtime rules directly.
- Legacy runtime is absorbed through maps/wrappers only; no isolated new runtime islands.
''')
dump('00_module_charter/s00_scope_boundary.yaml', meta('S00_SCOPE_BOUNDARY', consumer=['K00','P00','R00','P01-P10','P08','P09','P10'])|{'scope':{'in_scope':['goals','methods','entities','field_lineage','field_permissions','schema_contracts','runner_binding','trace_acceptance_handoff','R00 validation','P08 permission','P09/P10 review upgrade','issue task registry','legacy absorption','sample regression rollback','security boundary'],'out_of_scope':['real trading execution','private key handling','automatic live rule promotion','moving/deleting legacy runtime outputs'],'canonical_root':str(s00)}})
objects=[]
for typ,name in [('goal','Goal mapping'),('method','Method wheel mapping'),('schema','Schema index'),('contract','Contract index'),('runner','Runner binding'),('trace','Trace event'),('acceptance','Acceptance gate'),('handoff','Handoff packet'),('gate','P08 permission gate'),('review','P09/P10 review upgrade'),('security','Security boundary')]:
    objects.append({'standard_id':f'S00_{typ.upper()}_STANDARD','standard_name':name,'standard_type':typ,'owner_plane':'S00','applies_to_phases':['K00','P00','P01-P10','R00','P08','P09','P10'],'producer':'S00','consumer':['Phase Controllers','R00','paper runtime'],'source_files':['DOC-20260514-S00-001'],'output_files':[],'version':version,'status':'active_with_gaps','acceptance_required':True,'last_reviewed_at':now,'risk_level':'medium' if typ!='security' else 'high'})
dump('00_module_charter/s00_standard_object_registry.yaml', meta('S00_STANDARD_OBJECT_REGISTRY')|{'standard_objects':objects})
ids={'token_id':'chain:address','wallet_id':'chain:wallet_address','cluster_id':'chain:token:cluster_hash','event_id':'timestamp:source:hash','phase_run_id':'phase_id:token_id:run_timestamp','decision_id':'phase_id:token_id:decision_timestamp','trace_id':'run_id:event_sequence','handoff_id':'source_phase:target_phase:token_id:timestamp','review_case_id':'P09:token_id:paper_position_id:timestamp','upgrade_candidate_id':'P10:review_case_id:rule_hash'}
dump('01_global_identity/global_id_standard.yaml', meta('S00_GLOBAL_ID_STANDARD')|{'id_patterns':ids,'acceptance_rule':'Every token judgment case file must include token_id, analysis_run_id, trace_refs, acceptance_refs, handoff_refs.'})
dump('01_global_identity/global_status_code_table.yaml', meta('S00_GLOBAL_STATUS_CODE_TABLE')|{'s00_status_codes':['S00_NOT_STARTED','S00_STRUCTURE_CREATED','S00_STANDARD_OBJECTS_DEFINED','S00_PHASES_MAPPED','S00_RUNNERS_BOUND','S00_TRACE_ACCEPTANCE_READY','S00_R00_VALIDATED','S00_P08_BOUND','S00_P09_P10_BOUND','S00_LEGACY_ABSORBED','S00_REGRESSION_READY','S00_PROFESSIONAL_READY_WITH_GAPS','S00_PROFESSIONAL_READY','S00_REJECTED'],'runtime_status':['READY','READY_WITH_GAPS','BLOCKED','REJECTED','PASS','PASS_WITH_GAPS','FAIL','WITH_GAPS'],'current_status':'S00_TRACE_ACCEPTANCE_RUNNER_BOUND_READY_WITH_GAPS'})
dump('01_global_identity/global_event_type_registry.yaml', meta('S00_GLOBAL_EVENT_TYPE_REGISTRY')|{'event_types':['SOURCE_REGISTERED','PHASE_STARTED','RUNNER_STARTED','RUNNER_OUTPUT_WRITTEN','SCHEMA_VALIDATED','ACCEPTANCE_PASSED','ACCEPTANCE_WITH_GAPS','HANDOFF_CREATED','P08_PERMISSION_EVALUATED','P09_REVIEW_CASE_CREATED','P10_UPGRADE_CANDIDATE_CREATED','ROLLBACK_TRIGGERED','SECURITY_BLOCKED']})
base_goal={'goal_id':'S00_GOAL_TOKEN_JUDGMENT_TRACEABLE','goal_name':'真实 token 阶段化判断闭环可追溯','goal_type':'system','goal_statement':'任意 token 判断可反向追溯目标/方法/输入/字段血缘/schema/contract/runner/trace/acceptance/handoff/P08/P09/P10。','success_definition':'token_judgment_case_file contains all required refs','related_phases':['P01','P02','P03','P04','P05','P06','P07','P08','P09','P10'],'required_inputs':['data_fact_handoff_packet','wallet/chip/scenario/evidence/strategy handoffs'],'required_outputs':['token_judgment_case_file','P08 permission result','P09 review case if paper result exists'],'required_decisions':['paper permission','observe/block/ready'],'required_evidence':['positive_evidence','counter_evidence','field_lineage'],'required_runners':['phase runners','R00 validators'],'acceptance_gate':'S00_TOKEN_JUDGMENT_ACCEPTANCE','downstream_consumer':'paper-only runtime / review upgrade'}
dump('02_goal_mapping/system_goal_mapping.yaml', meta('S00_SYSTEM_GOAL_MAPPING')|{'goals':[base_goal]})
dump('02_goal_mapping/token_judgment_goal_map.yaml', meta('S00_TOKEN_JUDGMENT_GOAL_MAP')|{'token_judgment_required_refs':['goal_refs','method_refs','input_data_refs','field_lineage_refs','schema_refs','contract_refs','runner_refs','trace_refs','acceptance_refs','handoff_refs','permission_gate_result','paper_decision','review_status','upgrade_candidate_refs','known_gaps']})
phases=['K00','P00','P01','P02','P03','P04','P05','P06','P07','P08','P09','P10','R00']
dump('02_goal_mapping/phase_goal_alignment_matrix.yaml', meta('S00_PHASE_GOAL_ALIGNMENT_MATRIX')|{'phase_alignment':[{'phase_id':p,'required_goal_refs':['S00_GOAL_TOKEN_JUDGMENT_TRACEABLE'] if p.startswith('P') else ['S00_GOAL_SYSTEM_CONTROL']} for p in phases]})
dump('02_goal_mapping/goal_to_runner_consumption_map.yaml', meta('S00_GOAL_TO_RUNNER_CONSUMPTION_MAP')|{'mappings':[{'goal_id':'S00_GOAL_TOKEN_JUDGMENT_TRACEABLE','phase_controller':'P01-P10','runner_refs':['RUNNER_SIKK_LIVE_RUN_LEGACY','RUNNER_FULL_SYSTEM_RUNNER','RUNNER_PHASE_RUNNER'],'status':'mapped_with_gaps'}]})
method={'method_id':'MW_WALLET_CHIP_DOMINANT_SIDE_001','method_name':'钱包筹码主导侧生命周期判断','method_source':'uploaded S00 v2.0 spec','method_purpose':'convert wallet/chip behavior into staged evidence and counter-evidence','applies_to':['P03_wallet_entity','P04_chip_structure','P05_evidence','P06_scenario_recognition'],'phase_bindings':['P03','P04','P05','P06'],'input_fields':['wallet_holding_delta','same_source_group_id','sync_sell_score','counterparty_pressure_score','market_cap_change_from_discovery_pct'],'derived_fields':['dominant_side_status','chip_control_retention','distribution_progress','reaccumulation_possibility'],'decision_outputs':['scenario_candidate','strategy_gate_input'],'counter_evidence_required':['early_wallet_concentrated_exit','quote_liquidity_inconsistency','falling_obv','negative_cmf'],'confidence_model':'evidence + counter-evidence + data_quality_score','failure_conditions':['missing lineage','missing counter evidence','schema validation fail'],'sample_cases':[],'regression_tests':[]}
dump('03_method_wheel_mapping/method_wheel_registry.yaml', meta('S00_METHOD_WHEEL_REGISTRY')|{'methods':[method]})
for fn,key in [('method_to_phase_map.yaml','phase_bindings'),('method_to_field_map.yaml','input_fields'),('method_to_decision_map.yaml','decision_outputs'),('method_to_counter_evidence_map.yaml','counter_evidence_required')]: dump('03_method_wheel_mapping/'+fn, meta('S00_'+fn[:-5].upper())|{'method_id':method['method_id'], key:method[key]})
entities=['token','wallet','cluster','trade_event','market_snapshot','signal','evidence','counter_evidence','decision','handoff_packet','paper_position','review_case','upgrade_candidate']
dump('04_domain_entity_model/canonical_entity_model.yaml', meta('S00_CANONICAL_ENTITY_MODEL')|{'entities':[{'entity':e,'id_field': e+'_id' if e not in ['token','wallet','cluster'] else {'token':'token_id','wallet':'wallet_id','cluster':'cluster_id'}[e], 'evidence_required': e in ['signal','decision','paper_position','review_case','upgrade_candidate']} for e in entities]})
for fn,entity,fields in [('token_entity_schema.yaml','token',['token_id','chain','address','symbol','name','market_snapshot_refs','data_quality_score']),('wallet_entity_schema.yaml','wallet',['wallet_id','chain','wallet_address','role','cluster_id','evidence_refs']),('cluster_entity_schema.yaml','cluster',['cluster_id','token_id','wallet_refs','cluster_type','confidence_level']),('trade_event_schema.yaml','trade_event',['event_id','token_id','wallet_id','side','amount','price','source','event_time']),('signal_entity_schema.yaml','signal',['signal_id','token_id','signal_type','evidence_refs','counter_evidence_refs','confidence_level']),('decision_entity_schema.yaml','decision',['decision_id','phase_id','token_id','decision_status','evidence_refs','counter_evidence_refs','acceptance_ref']),('paper_position_entity_schema.yaml','paper_position',['paper_position_id','token_id','permission_ref','entry_decision_id','status','no_real_trade'])]: dump('04_domain_entity_model/'+fn, meta('S00_'+entity.upper()+'_ENTITY_SCHEMA')|{'entity':entity,'required_fields':fields,'schema_version':version,'validation':'R00 schema validation pending'})
sources=[{'source_id':'SRC_GMGN_LEGACY_RUNTIME','source_type':'legacy_runtime','path':'/root/sikk-gmgn/data/gmgn_candidates_live_run','status':'keep_in_place_readonly_compat'},{'source_id':'SRC_SOURCE_WALLET_BOT','source_type':'canonical_wallet_source','path':'/root/sikk-gmgn/data/source_wallet_bot/<mode>/<token>','status':'canonical_new_wallet_outputs'}]
dump('05_data_lineage/data_source_registry.yaml', meta('S00_DATA_SOURCE_REGISTRY')|{'sources':sources})
lineage=[]
for field,entity,stype in [('dominant_side_status','decision','inferred'),('chip_control_retention','signal','derived'),('distribution_progress','signal','derived'),('permission_status','paper_position','decision'),('review_case_id','review_case','decision')]: lineage.append({'field_name':field,'entity':entity,'source_type':stype,'source_file':'TBD_BY_PHASE_RUNNER','source_api':None,'source_runner':'TBD_BOUND_RUNNER','source_phase':'TBD','transform_function':'TBD','depends_on_fields':[],'generated_at':None,'schema_version':version,'confidence_level':'WITH_GAPS','data_quality_score':None,'consumed_by':[{'phase_id':'P08' if field=='permission_status' else 'P05/P06/P09','runner_id':'TBD','decision_field':field}]})
dump('05_data_lineage/field_lineage_registry.yaml', meta('S00_FIELD_LINEAGE_REGISTRY')|{'field_lineage':lineage,'blocking_rule':'Unlineaged decision fields cannot enter P07/P08/paper runner except as observe-only.'})
dump('05_data_lineage/file_lineage_map.yaml', meta('S00_FILE_LINEAGE_MAP')|{'file_maps':[{'file':'data/gmgn_candidates_live_run/**','source':'legacy runtime','new_mapping':'14_legacy_absorption/legacy_to_new_mapping.yaml'}]})
dump('05_data_lineage/decision_lineage_map.yaml', meta('S00_DECISION_LINEAGE_MAP')|{'decision_fields':['dominant_side_status','permission_status','paper_decision'],'lineage_required':True})
dump('05_data_lineage/report_lineage_map.yaml', meta('S00_REPORT_LINEAGE_MAP')|{'reports':['daily report','dashboard/static site','token_judgment_case_file'],'required_lineage_refs':['input_data_refs','decision_refs','acceptance_refs']})
classes={'raw_fact':'forbidden_manual_write','normalized_fact':'runner_rebuild_only','derived_metric':'runner_recompute','inferred_state':'evidence_update_only','decision_field':'phase_controller_only','permission_field':'P08_or_control_plane_only','review_field':'P09_only','upgrade_field':'P10_only','manual_note':'manual_allowed_not_for_auto_decision'}
perm=[]
for field,cls in [('gmgn_raw_snapshot','raw_fact'),('dominant_side_status','decision_field'),('permission_status','permission_field'),('review_case_id','review_field'),('upgrade_candidate_id','upgrade_field'),('analyst_note','manual_note')]: perm.append({'field_name':field,'entity':'mixed','field_class':cls,'write_permission':classes[cls],'read_permission':'allowed_by_contract','allowed_writers':[classes[cls]],'allowed_consumers':['Phase Controllers','R00','reports'],'manual_override_allowed':cls=='manual_note','requires_trace_event':True,'requires_acceptance':cls!='manual_note','prohibited_usage':['real_trade_authorization']})
dump('06_field_governance/field_permission_matrix.yaml', meta('S00_FIELD_PERMISSION_MATRIX')|{'field_permissions':perm})
dump('06_field_governance/field_mutation_policy.yaml', meta('S00_FIELD_MUTATION_POLICY')|{'rules':classes,'hard_rule':'raw_fact and permission_field cannot be manually mutated by analysis runner.'})
dump('06_field_governance/field_confidence_policy.yaml', meta('S00_FIELD_CONFIDENCE_POLICY')|{'confidence_levels':['HIGH','MEDIUM','LOW','UNKNOWN','WITH_GAPS'],'rule':'decision fields require confidence_level and counter_evidence_refs.'})
dump('06_field_governance/field_manual_override_policy.yaml', meta('S00_FIELD_MANUAL_OVERRIDE_POLICY')|{'manual_override_allowed_for':['manual_note'],'manual_override_forbidden_for':['raw_fact','permission_field','upgrade_field'],'trace_required':True})
contract_entries=[]
for p in ['P01','P02','P03','P04','P05','P06','P07','P08','P09','P10']:
    contract_entries.append({'contract_id':f'{p}_STANDARD_CONTRACT_SET','contract_name':f'{p} input/output/handoff/trace/acceptance/failure contracts','producer_phase':p,'consumer_phase':'next_phase_or_control_plane','required_files':[f'{p.lower()}_input_contract',f'{p.lower()}_output_contract',f'{p.lower()}_handoff_contract'],'required_fields':['token_id','phase_run_id','trace_refs','acceptance_status','handoff_status'],'optional_fields':['known_gaps','counter_evidence_refs'],'forbidden_fields':['private_key','signed_transaction','broadcast_tx','real_swap_order'],'schema_version':version,'validation_runner':'R00_VALIDATION_CONTROLLER','acceptance_gate':f'{p}_ACCEPTANCE_GATE','failure_policy':'BLOCK_OR_DEGRADE_WITH_EXPLICIT_REASON','handoff_packet':f'{p}_HANDOFF_PACKET'})
dump('07_schema_contract/schema_index.yaml', meta('S00_SCHEMA_INDEX')|{'schemas':[{'schema_id':c['contract_id'].replace('CONTRACT_SET','SCHEMA_SET'),'phase':c['producer_phase'],'version':version,'status':'defined_with_gaps'} for c in contract_entries]})
dump('07_schema_contract/contract_index.yaml', meta('S00_CONTRACT_INDEX')|{'contracts':contract_entries})
dump('07_schema_contract/phase_input_contracts.yaml', meta('S00_PHASE_INPUT_CONTRACTS')|{'phase_input_contracts':[{'phase':c['producer_phase'],'input_contract':c['required_files'][0],'required_refs':['upstream_handoff','token_id','source_refs']} for c in contract_entries]})
dump('07_schema_contract/phase_output_contracts.yaml', meta('S00_PHASE_OUTPUT_CONTRACTS')|{'phase_output_contracts':[{'phase':c['producer_phase'],'output_contract':c['required_files'][1],'required_refs':['trace','acceptance','handoff']} for c in contract_entries]})
dump('07_schema_contract/handoff_contracts.yaml', meta('S00_HANDOFF_CONTRACTS')|{'handoff_contracts':[{'phase':c['producer_phase'],'handoff_contract':c['handoff_packet'],'failure_policy':c['failure_policy']} for c in contract_entries]})
dump('07_schema_contract/report_contracts.yaml', meta('S00_REPORT_CONTRACTS')|{'report_contracts':[{'report':'S00_ACCEPTANCE_REPORT','required_sections':['completed','with_gaps','blocking','verification','next_route']},{'report':'token_judgment_case_file','required_refs':['goal_refs','method_refs','lineage_refs','P08','P09/P10']}]})
dump('07_schema_contract/backward_compatibility_policy.yaml', meta('S00_BACKWARD_COMPATIBILITY_POLICY')|{'policy':'legacy outputs are read through mapping/wrappers; no direct downstream reads unless S00 mapping authorizes fallback','failure_strategy':'degrade_with_explicit_legacy_gap'})
runners=[{'runner_id':'RUNNER_SIKK_LIVE_RUN_LEGACY','runner_name':'sikk_live_run.py','runner_type':'ingestion_analysis_paper_legacy','script_path':'/root/sikk-gmgn/sikk_live_run.py','entry_command':'python3 sikk_live_run.py --output-root data/gmgn_candidates_live_run --limit 50 --quote-sources okx --default-quote-amount-sol 0.01 --mode once','bound_phase':'LEGACY_RUNTIME_COMPAT_TO_P01_P08_REVIEW','input_contract':'legacy_runtime_input_contract','output_contract':'legacy_runtime_output_contract','writes_trace':'WITH_GAPS','writes_acceptance':'WITH_GAPS','writes_handoff':'WITH_GAPS','allowed_modes':['dry_run','replay','paper_only'],'forbidden_modes':['live_swap','sign','broadcast'],'failure_policy':'legacy failure recorded in R00 failure report','timeout_policy':'TBD_R00','rollback_policy':'no mutation; keep outputs versioned'},{'runner_id':'RUNNER_GMGN_PIPELINE_LEGACY','runner_name':'run_sikk_gmgn_pipeline.py','runner_type':'analysis_legacy','script_path':'/root/sikk-gmgn/run_sikk_gmgn_pipeline.py','entry_command':'python3 run_sikk_gmgn_pipeline.py --help','bound_phase':'LEGACY_RUNTIME_COMPAT','input_contract':'legacy_runtime_input_contract','output_contract':'legacy_runtime_output_contract','writes_trace':'WITH_GAPS','writes_acceptance':'WITH_GAPS','writes_handoff':'WITH_GAPS','allowed_modes':['dry_run','replay'],'forbidden_modes':['live_swap','sign','broadcast'],'failure_policy':'R00_WRAP_REQUIRED','timeout_policy':'TBD_R00','rollback_policy':'no mutation'},{'runner_id':'RUNNER_FULL_SYSTEM_RUNNER','runner_name':'modules.runtime.full_system_runner','runner_type':'replay_validation','script_path':'/root/sikk-gmgn/modules/runtime/full_system_runner.py','entry_command':'python3 -m modules.runtime.full_system_runner --help','bound_phase':'P01_P10_REPLAY','input_contract':'full_system_replay_input_contract','output_contract':'full_system_replay_output_contract','writes_trace':'expected','writes_acceptance':'expected','writes_handoff':'expected','allowed_modes':['dry_run','replay','paper_only'],'forbidden_modes':['live_swap','sign','broadcast'],'failure_policy':'READY_WITH_GAPS if degraded only; BLOCKED if safety missing','timeout_policy':'TBD_R00','rollback_policy':'checkpoint rollback only'},{'runner_id':'RUNNER_PHASE_RUNNER','runner_name':'modules.runtime.phase_runner','runner_type':'phase_replay','script_path':'/root/sikk-gmgn/modules/runtime/phase_runner.py','entry_command':'python3 -m modules.runtime.phase_runner --help','bound_phase':'P01_P10','input_contract':'phase_input_contract','output_contract':'phase_output_contract','writes_trace':'expected','writes_acceptance':'expected','writes_handoff':'expected','allowed_modes':['dry_run','replay'],'forbidden_modes':['live_swap','sign','broadcast'],'failure_policy':'phase-specific block/degrade','timeout_policy':'TBD_R00','rollback_policy':'replay artifact rollback'}]
dump('08_runner_binding/runner_registry.yaml', meta('S00_RUNNER_REGISTRY')|{'runners':runners})
dump('08_runner_binding/phase_runner_binding.yaml', meta('S00_PHASE_RUNNER_BINDING')|{'bindings':[{'phase':'P01-P10','runner_id':'RUNNER_PHASE_RUNNER','status':'bound_with_gaps'},{'phase':'P08','runner_id':'RUNNER_FULL_SYSTEM_RUNNER','status':'bound_with_gaps'},{'phase':'legacy_runtime','runner_id':'RUNNER_SIKK_LIVE_RUN_LEGACY','status':'absorbed_with_gaps'}]})
dump('08_runner_binding/validation_runner_registry.yaml', meta('S00_VALIDATION_RUNNER_REGISTRY')|{'validation_runners':[{'runner_id':'R00_VALIDATION_CONTROLLER','purpose':'validate script existence, command dry-run, schema, trace, acceptance, handoff, controller bypass'}]})
dump('08_runner_binding/replay_runner_registry.yaml', meta('S00_REPLAY_RUNNER_REGISTRY')|{'replay_runners':[r for r in runners if 'replay' in r['allowed_modes']]})
dump('08_runner_binding/paper_runner_binding.yaml', meta('S00_PAPER_RUNNER_BINDING')|{'paper_boundary':'P08 permission gate required before paper open; real trade forbidden','paper_runners':[{'runner_id':'RUNNER_SIKK_LIVE_RUN_LEGACY','requires_p08_permission':True,'status':'legacy_absorbed_with_p08_gap'}]})
dump('08_runner_binding/runner_failure_policy.yaml', meta('S00_RUNNER_FAILURE_POLICY')|{'failure_policy':['missing script -> BLOCKED','schema mismatch -> BLOCKED or WITH_GAPS if non-decision optional','missing trace/acceptance/handoff -> WITH_GAPS until R00 wrapper exists','attempted live_swap/sign/broadcast -> SECURITY_BLOCKED']})
dump('08_runner_binding/runner_output_contract_map.yaml', meta('S00_RUNNER_OUTPUT_CONTRACT_MAP')|{'maps':[{'runner_id':r['runner_id'],'output_contract':r['output_contract'],'phase':r['bound_phase']} for r in runners]})
trace_schema={'trace_id':'run_id:event_sequence','run_id':'required','token_id':'required_if_token_task','phase_id':'required','runner_id':'required','event_type':'registered_event_type','event_time':'ISO8601','input_refs':'list','output_refs':'list','decision_refs':'list','status_before':'string','status_after':'string','evidence_refs':'list','counter_evidence_refs':'list','error_refs':'list','schema_version':version}
dump('09_trace_acceptance_handoff/trace_event_schema.yaml', meta('S00_TRACE_EVENT_SCHEMA')|{'trace_event_schema':trace_schema})
dump('09_trace_acceptance_handoff/process_trace_policy.yaml', meta('S00_PROCESS_TRACE_POLICY')|{'policy':'Every runner and phase transition writes a trace event or is marked R00_WITH_GAPS.'})
dump('09_trace_acceptance_handoff/acceptance_gate_matrix.yaml', meta('S00_ACCEPTANCE_GATE_MATRIX')|{'gates':[{'phase':p,'required_checks':['schema_validation','runner_validation','data_quality','decision_quality','handoff_presence'],'status_values':['PASS','WITH_GAPS','FAIL']} for p in ['P01','P02','P03','P04','P05','P06','P07','P08','P09','P10']]})
dump('09_trace_acceptance_handoff/acceptance_evidence_schema.yaml', meta('S00_ACCEPTANCE_EVIDENCE_SCHEMA')|{'required_fields':['acceptance_id','phase_id','token_id','run_id','required_checks','passed_checks','failed_checks','missing_fields','schema_validation_result','runner_validation_result','data_quality_result','decision_quality_result','status','blocking_reason','next_allowed_phase']})
dump('09_trace_acceptance_handoff/handoff_packet_standard.yaml', meta('S00_HANDOFF_PACKET_STANDARD')|{'required_fields':['handoff_id','source_phase','target_phase','token_id','handoff_status','required_payload','payload_files','decision_summary','evidence_summary','counter_evidence_summary','data_quality_summary','known_gaps','next_phase_permissions']})
dump('09_trace_acceptance_handoff/downstream_consumption_matrix.yaml', meta('S00_DOWNSTREAM_CONSUMPTION_MATRIX')|{'consumption':[{'producer':'P01','consumer':'P02/P08','artifact':'data_fact_handoff_packet'},{'producer':'P07','consumer':'P08','artifact':'strategy_gate_decision'},{'producer':'P08','consumer':'paper runner/P09','artifact':'permission_gate_result'},{'producer':'P09','consumer':'P10','artifact':'review_case'}]})
md('10_validation_r00/r00_validation_controller.md', f'''# R00 Validation Controller

- producer: S00_unified_system_standardization
- consumer: R00 / HER Control Plane
- version: {version}
- status: active_with_gaps
- acceptance: validates runner binding, command dry-run, input/output contract, trace, acceptance, handoff and no Phase Controller bypass.

R00 不负责交易判断，只负责系统组件是否正确绑定、运行、输出、交接。
''')
dump('10_validation_r00/r00_validation_checklist.yaml', meta('S00_R00_VALIDATION_CHECKLIST')|{'checks':['script_exists','entry_command_help_or_dry_run','input_contract_parse','output_schema_parse','trace_written','acceptance_generated','handoff_consumable','phase_controller_binding','security_no_live_swap']})
dump('10_validation_r00/r00_runner_dry_run_matrix.yaml', meta('S00_R00_RUNNER_DRY_RUN_MATRIX')|{'dry_runs':[{'runner_id':r['runner_id'],'command':r['entry_command'],'status':'pending_r00_execution'} for r in runners]})
dump('10_validation_r00/r00_replay_validation_matrix.yaml', meta('S00_R00_REPLAY_VALIDATION_MATRIX')|{'replay_validations':[{'target':'single_token_full_chain_replay','status':'pending','requires':['sample token','P01-P10 contracts','P08 gate','P09/P10 review package']}]})
dump('10_validation_r00/r00_failure_report_schema.yaml', meta('S00_R00_FAILURE_REPORT_SCHEMA')|{'required_fields':['failure_id','runner_id','phase_id','failure_type','symptom','root_cause_hypothesis','evidence_refs','blocking_status','recovery_action','next_validation']})
pstats=['BLOCKED','WATCH_ONLY','PAPER_ELIGIBLE','PAPER_READY','PAPER_ACTIVE','EXIT_MONITOR','FORCE_PAPER_EXIT','READY_FOR_CONFIRMATION','REAL_TRADE_FORBIDDEN']
dump('11_permission_gate_p08/p08_permission_gate_policy.yaml', meta('S00_P08_PERMISSION_GATE_POLICY')|{'permission_status':pstats,'required_inputs':['P01 data_fact_handoff_packet','P02/P03 wallet/chip handoff','P04 chip structure result','P05 evidence/counter-evidence','P06 scenario recognition','P07 strategy gate decision','quote/security result','wallet_structure_decision','market_cap_context','trace/acceptance status'],'hard_rules':['No P08 pass -> no paper open','No manual confirmation -> no real trade','P09/P10 cannot directly mutate P08 live rule']})
dump('11_permission_gate_p08/p08_action_permission_matrix.yaml', meta('S00_P08_ACTION_PERMISSION_MATRIX')|{'actions':[{'action':'open_paper_position','allowed_status':['PAPER_READY'],'forbidden_if':['missing_trace','missing_acceptance','REAL_TRADE_FORBIDDEN only without PAPER_READY']},{'action':'real_swap','allowed_status':[],'forbidden_if':['always_for_current_system']}]})
dump('11_permission_gate_p08/p08_paper_only_boundary.yaml', meta('S00_P08_PAPER_ONLY_BOUNDARY')|{'paper_only':True,'requires_permission_status':['PAPER_READY','PAPER_ACTIVE','EXIT_MONITOR'],'no_signing':True,'no_broadcast':True})
dump('11_permission_gate_p08/p08_real_trade_forbidden_policy.yaml', meta('S00_P08_REAL_TRADE_FORBIDDEN_POLICY')|{'real_trade_default':'FORBIDDEN','forbidden_actions':['swap','sign','broadcast','private_key_access','unreviewed_api_key_trade_permission'],'manual_confirmation_required_for_any_future_real_trade':True})
dump('11_permission_gate_p08/p08_risk_event_schema.yaml', meta('S00_P08_RISK_EVENT_SCHEMA')|{'required_fields':['risk_event_id','token_id','permission_status_before','permission_status_after','trigger','evidence_refs','counter_evidence_refs','action_required','trace_id']})
for fn,fields in [('p09_review_case_schema.yaml',['review_case_id','token_id','paper_position_id','entry_decision_id','exit_decision_id','expected_scenario','actual_outcome','failure_type','success_type','missed_counter_evidence','wrong_assumption','data_gap','runner_gap','rule_gap','recommended_action']),('p09_failure_attribution_schema.yaml',['failure_id','review_case_id','failure_type','root_cause','evidence_refs','recommended_action']),('p09_replay_packet_schema.yaml',['replay_packet_id','review_case_id','input_refs','expected_result','actual_result','diff','status']),('p10_upgrade_candidate_schema.yaml',['upgrade_candidate_id','source_review_case','affected_rule','affected_phase','change_proposal','expected_improvement','risk_of_change','shadow_test_required','regression_test_required','rollback_plan','approval_status','promotion_status'])]: dump('12_review_upgrade_p09_p10/'+fn, meta('S00_'+fn[:-5].upper())|{'required_fields':fields})
dump('12_review_upgrade_p09_p10/p10_shadow_validation_policy.yaml', meta('S00_P10_SHADOW_VALIDATION_POLICY')|{'promotion_path':['review_case','upgrade_candidate','shadow_validation','regression_test','rollback_plan','approval','versioned_promotion'],'allow_apply_to_runtime':False})
dump('12_review_upgrade_p09_p10/p10_rule_promotion_policy.yaml', meta('S00_P10_RULE_PROMOTION_POLICY')|{'requires':['approval','regression_pass','rollback_plan','version_increment','manual_confirmation'],'direct_runtime_mutation_forbidden':True})
dump('13_issue_task_registry/issue_registry.yaml', meta('S00_ISSUE_REGISTRY')|{'issues':[],'initial_known_gaps':['runner dry-run pending','contract diff pending','sample library empty','P08 paper runner connection pending']})
dump('13_issue_task_registry/issue_taxonomy.yaml', meta('S00_ISSUE_TAXONOMY')|{'issue_types':['schema_gap','contract_gap','runner_gap','trace_gap','acceptance_gap','handoff_gap','permission_gap','review_upgrade_gap','legacy_absorption_gap','security_violation']})
dump('13_issue_task_registry/task_packet_schema.yaml', meta('S00_TASK_PACKET_SCHEMA')|{'required_fields':['task_packet_id','source_issue_id','task_goal','scope','non_goals','files_to_create','files_to_modify','commands_to_run','validation_steps','acceptance_criteria','rollback_plan','handoff_target','completion_status']})
dump('13_issue_task_registry/task_priority_policy.yaml', meta('S00_TASK_PRIORITY_POLICY')|{'priority_order':['security_violation','permission_gap','runner_gap','contract_gap','trace_acceptance_handoff_gap','legacy_absorption_gap','regression_gap']})
dump('13_issue_task_registry/task_acceptance_policy.yaml', meta('S00_TASK_ACCEPTANCE_POLICY')|{'rule':'issue without task packet is not in repair flow; task packet without acceptance is not complete'})
legacy=[{'legacy_asset_id':'LEGACY_GMGN_CANDIDATES_LIVE_RUN','legacy_path':'/root/sikk-gmgn/data/gmgn_candidates_live_run','asset_type':'legacy_runtime_output_root','current_usage':'sikk_live_run runtime compatibility outputs, site, paper_live, reports','new_system_mapping':'read through S00 absorption map; no new primary writes except legacy-compatible runner','absorption_mode':'keep_in_place','risk_level':'medium','consumer':['legacy dashboard','paper reports','S00 R00 validators'],'replacement_plan':'wrap outputs into trace/acceptance/handoff and migrate new source-wallet data to data/source_wallet_bot','validation_required':True},{'legacy_asset_id':'LEGACY_SIKK_LIVE_RUN_SCRIPT','legacy_path':'/root/sikk-gmgn/sikk_live_run.py','asset_type':'legacy_runner','current_usage':'main legacy runtime entry','new_system_mapping':'RUNNER_SIKK_LIVE_RUN_LEGACY','absorption_mode':'wrap_runner','risk_level':'high','consumer':['R00','P08 paper gate future wrapper'],'replacement_plan':'do not delete; add wrapper/contract validation','validation_required':True}]
dump('14_legacy_absorption/legacy_asset_inventory.yaml', meta('S00_LEGACY_ASSET_INVENTORY')|{'legacy_assets':legacy})
dump('14_legacy_absorption/legacy_to_new_mapping.yaml', meta('S00_LEGACY_TO_NEW_MAPPING')|{'mappings':[{'legacy_asset_id':l['legacy_asset_id'],'new_mapping':l['new_system_mapping'],'absorption_mode':l['absorption_mode']} for l in legacy]})
dump('14_legacy_absorption/legacy_runtime_absorption_plan.yaml', meta('S00_LEGACY_RUNTIME_ABSORPTION_PLAN')|{'plan_steps':['keep old scripts/path','register runners','bind to phase_runner_binding','add trace/acceptance/handoff wrapper','R00 dry-run validation','single-token replay validation']})
dump('14_legacy_absorption/legacy_keep_deprecate_migrate_policy.yaml', meta('S00_LEGACY_KEEP_DEPRECATE_MIGRATE_POLICY')|{'modes':['keep_in_place','wrap_runner','migrate_output','deprecate','archive'],'default':'keep_in_place until contract-compatible replacement passes regression'})
dump('14_legacy_absorption/legacy_readonly_boundary.yaml', meta('S00_LEGACY_READONLY_BOUNDARY')|{'readonly_for_downstream':True,'new_primary_fact_writes':'/root/sikk-gmgn/data/source_wallet_bot/<mode>/<token>/','no_delete_or_move':True})
samples=['confirmed_distribution','failed_breakout','second_stage_expansion','long_control_box','wallet_exit_failure','paper_success_case','paper_failure_case','false_positive','false_negative']
dump('15_sample_regression_rollback/sample_library_index.yaml', meta('S00_SAMPLE_LIBRARY_INDEX')|{'sample_types':samples,'samples':[],'status':'empty_with_gap'})
dump('15_sample_regression_rollback/labeled_token_case_schema.yaml', meta('S00_LABELED_TOKEN_CASE_SCHEMA')|{'required_fields':['case_id','token_id','sample_type','label_source','phase_outputs','expected_decision','actual_decision','evidence_refs','counter_evidence_refs']})
dump('15_sample_regression_rollback/regression_suite_registry.yaml', meta('S00_REGRESSION_SUITE_REGISTRY')|{'suites':[{'suite_id':'S00_REGRESSION_BASELINE','sample_types':samples,'status':'pending_samples'}]})
dump('15_sample_regression_rollback/regression_result_schema.yaml', meta('S00_REGRESSION_RESULT_SCHEMA')|{'required_fields':['regression_run_id','suite_id','rule_version_before','rule_version_after','passed_cases','failed_cases','false_positive_delta','false_negative_delta','p08_impact','paper_runner_impact','rollback_required']})
dump('15_sample_regression_rollback/rollback_policy.yaml', meta('S00_ROLLBACK_POLICY')|{'rollback_required_if':['regression_fail','P08 permission degradation','paper_runner safety violation','increased false positives without approval'],'requires_versioned_rule_registry':True})
dump('15_sample_regression_rollback/rule_version_registry.yaml', meta('S00_RULE_VERSION_REGISTRY')|{'rule_versions':[{'rule_set':'S00_INITIAL_STANDARD_RULES','version':version,'status':'active_with_gaps','rollback_to':None}]})
sec={'default_execution_mode':'paper_only','real_trade':'forbidden','private_key_access':'forbidden','signing':'forbidden','broadcast':'forbidden','p08_required_for_paper':True,'manual_confirmation_required_for_future_real_trade':True}
dump('16_security_boundary/security_boundary_policy.yaml', meta('S00_SECURITY_BOUNDARY_POLICY')|sec)
dump('16_security_boundary/paper_only_execution_policy.yaml', meta('S00_PAPER_ONLY_EXECUTION_POLICY')|{'paper_only':True,'allowed':['observe','dry_run','replay','paper_position_simulation'],'forbidden':['swap','sign','broadcast']})
dump('16_security_boundary/real_trade_forbidden_policy.yaml', meta('S00_REAL_TRADE_FORBIDDEN_POLICY')|{'real_trade_forbidden':True,'applies_to':['all runners','all phases','all legacy runtime wrappers']})
dump('16_security_boundary/api_key_permission_policy.yaml', meta('S00_API_KEY_PERMISSION_POLICY')|{'api_keys':'read-only or quote/data-only by default','forbidden_permissions':['withdraw','trade_without_manual_confirmation','signing'],'secret_storage':'do_not_write_to_history_or_repo'})
dump('16_security_boundary/manual_confirmation_policy.yaml', meta('S00_MANUAL_CONFIRMATION_POLICY')|{'required_for':['any future real trade','rule promotion to runtime','permission boundary change'],'current_real_trade_allowed':False})
dump('16_security_boundary/emergency_stop_policy.yaml', meta('S00_EMERGENCY_STOP_POLICY')|{'emergency_stop_triggers':['attempted live_swap','attempted sign','attempted broadcast','P08 bypass','private key access'],'result':'SECURITY_BLOCKED'})
all_rels=[f'{d}/{f}' for d,fs in files_by_dir.items() for f in fs]
dump('index/unified_standardization_index.yaml', meta('S00_UNIFIED_STANDARDIZATION_INDEX')|{'module_root':str(s00),'files':all_rels,'current_status':'S00_TRACE_ACCEPTANCE_RUNNER_BOUND_READY_WITH_GAPS','source_doc':'DOC-20260514-S00-001'})
dump('index/phase_consumption_matrix.yaml', meta('S00_PHASE_CONSUMPTION_MATRIX')|{'phase_consumption':[{'phase':p,'consumes':['input_contract','upstream_handoff','trace_policy'],'produces':['output_contract','acceptance','handoff']} for p in ['P01','P02','P03','P04','P05','P06','P07','P08','P09','P10']]})
dump('index/file_to_runner_index.yaml', meta('S00_FILE_TO_RUNNER_INDEX')|{'file_to_runner':[{'file':'data/gmgn_candidates_live_run/**','runner_id':'RUNNER_SIKK_LIVE_RUN_LEGACY'},{'file':'data/source_wallet_bot/<mode>/<token>/**','runner_id':'SOURCE_WALLET_BOT_TBD'}]})
dump('index/runner_to_phase_index.yaml', meta('S00_RUNNER_TO_PHASE_INDEX')|{'runner_to_phase':[{'runner_id':r['runner_id'],'bound_phase':r['bound_phase']} for r in runners]})
dump('index/schema_to_contract_index.yaml', meta('S00_SCHEMA_TO_CONTRACT_INDEX')|{'schema_to_contract':[{'schema_id':c['contract_id'].replace('CONTRACT_SET','SCHEMA_SET'),'contract_id':c['contract_id']} for c in contract_entries]})
dump('index/goal_to_phase_to_runner_index.yaml', meta('S00_GOAL_TO_PHASE_TO_RUNNER_INDEX')|{'entries':[{'goal_id':'S00_GOAL_TOKEN_JUDGMENT_TRACEABLE','phase':'P01-P10','runner_ids':['RUNNER_PHASE_RUNNER','RUNNER_FULL_SYSTEM_RUNNER','RUNNER_SIKK_LIVE_RUN_LEGACY'],'status':'mapped_with_gaps'}]})
dump('index/report_to_lineage_index.yaml', meta('S00_REPORT_TO_LINEAGE_INDEX')|{'reports':[{'report':'S00_ACCEPTANCE_REPORT.md','lineage_refs':['DOC-20260514-S00-001','K00 handoff','S00 index']},{'report':'token_judgment_case_file','lineage_refs':['field_lineage_registry','decision_lineage_map','report_lineage_map']}]})
for rel in all_rels:
    p=s00/rel
    if not p.exists():
        if p.suffix=='.md': md(rel, f'# {p.stem}\n\n- producer: S00_unified_system_standardization\n- consumer: HER/SIKK\n- version: {version}\n- status: {status}\n- acceptance: Parseable standard placeholder pending runtime binding.\n')
        else: dump(rel, meta('S00_'+p.stem.upper()))
print('S00_FILES_WRITTEN', len(all_rels), str(s00))
