
from __future__ import annotations

CHINESE_JUDGEMENT = {
    'address_role': {
        'NEW_SNIPER': '疑似新钱包狙击',
        'TEMP_EXEC': '疑似临时执行钱包',
        'SAME_SRC_MEMBER': '疑似同源执行组成员',
        'TOKEN_RECEIVER': '疑似 Token 接收钱包',
        'DISTRIBUTION_SELLER': '疑似分发派发钱包',
        'PROFIT_BACKFLOW': '疑似利润回收钱包',
        'CORE_FUND_SRC': '疑似核心资金源候选',
        'RESULT_WALLET': '疑似结果钱包',
        'BAGHOLDER_WHALE': '疑似接盘鲸鱼',
        'TRAPPED_WALLET': '疑似套牢钱包',
        'NORMAL_PARTICIPANT': '普通参与者',
        'NOISE_WALLET': '噪音钱包',
        'INFRA_WALLET': '基础设施地址',
        'UNKNOWN_ROLE': '角色未知',
    },
    'token_source': {
        'ACTIVE_BUY': '主动买入',
        'TOKEN_IN': 'Token 转入',
        'DISTRIBUTION_RECEIVE': '分发接收',
        'AIRDROP_RECEIVE': '空投接收',
        'UNKNOWN_SOURCE': '来源未知',
    },
    'funding_source': {
        'EXCHANGE_SOURCE': '交易所来源',
        'SINGLE_ADDRESS_SOURCE': '单一地址来源',
        'MULTI_ADDRESS_SOURCE': '多地址来源',
        'SAME_SOURCE_CLUSTER': '同源资金组',
        'BACKFLOW_SOURCE': '回流资金源',
        'POTENTIAL_CORE_SOURCE': '疑似核心资金源',
        'UNKNOWN_FUND_SOURCE': '资金来源未知',
    },
    'chip_transfer': {
        'CHIP_RETAINED': '筹码仍在结构侧',
        'CHIP_ROTATING': '结构侧部分轮换',
        'CHIP_TOWARD_COUNTERPARTY': '筹码转向对手盘',
        'ACTIVE_DISTRIBUTION': '疑似主动派发',
        'STRUCTURE_COLLAPSED': '结构侧崩塌',
        'CHIP_UNKNOWN': '筹码状态未知',
    },
    'wallet_structure': {
        'WALLET_SUPPORT': '钱包结构支持',
        'WALLET_NEUTRAL': '钱包结构中性',
        'WALLET_PAUSE': '钱包结构暂停',
        'WALLET_BLOCK': '钱包结构阻断',
        'WALLET_UNKNOWN': '钱包结构未知',
    },
    'lifecycle': {
        'EARLY_ACCUMULATION': '早期吸筹',
        'CONTROL_RANGE': '控盘箱体',
        'FIRST_RALLY': '一段拉升',
        'PARTIAL_DISTRIBUTION': '部分派发',
        'RE_ACCUMULATION': '再吸筹',
        'SECOND_STAGE_READY': '二段准备',
        'SECOND_STAGE_VOLUME': '二段放量',
        'ACTIVE_DISTRIBUTION': '主动派发',
        'STRUCTURE_COLLAPSE': '结构崩塌',
        'DEAD_SIDEWAYS': '死亡横盘',
        'RE_ACTIVATION': '再激活',
        'LIFECYCLE_UNKNOWN': '生命周期未知',
    },
    'motive': {
        'ACCUMULATE': '疑似吸筹',
        'CONTROL': '疑似控盘',
        'WASHOUT': '疑似洗盘',
        'BREAKOUT_TEST': '疑似测试突破',
        'MARKUP': '疑似推进拉升',
        'PARTIAL_DISTRIBUTION': '疑似部分派发',
        'ACTIVE_DISTRIBUTION': '疑似主动派发',
        'REACCUMULATION': '疑似再吸筹',
        'REACTIVATION': '疑似再激活',
        'ABANDONMENT': '疑似放弃维护',
        'POSSIBLE_ACCUMULATION': '疑似吸筹',
        'POSSIBLE_CONTROL': '疑似控盘',
        'POSSIBLE_WASHING': '疑似洗盘',
        'POSSIBLE_LIQUIDITY_TEST': '疑似流动性测试',
        'POSSIBLE_BREAKOUT_TEST': '疑似突破测试',
        'POSSIBLE_PUSH_UP': '疑似推进拉升',
        'POSSIBLE_PARTIAL_DISTRIBUTION': '疑似部分派发',
        'POSSIBLE_ACTIVE_DISTRIBUTION': '疑似主动派发',
        'POSSIBLE_RE_ACCUMULATION': '疑似再吸筹',
        'POSSIBLE_RE_ACTIVATION': '疑似再激活',
        'POSSIBLE_ABANDON_CONTROL': '疑似放弃维护',
        'MOTIVE_UNKNOWN': '行为动机未知',
    },
    'gate': {
        'ALLOW_PAPER_READY': '允许进入纸面交易',
        'CONTINUE_WATCHING': '继续观察',
        'PAUSE_FOR_CONFIRMATION': '暂停等待确认',
        'BLOCK': '阻断',
        'EXPIRED': '已过期',
        'GATE_UNKNOWN': '门禁状态未知',
    },
    'time': {
        'TIME_SYNC': '时间同步',
        'TIME_PARTIAL_SYNC': '时间部分同步',
        'TIME_DESYNC': '时间不同步',
        'TIME_UNKNOWN': '时间未知',
        'DATA_EXPIRED': '数据过期',
        'NEED_REFRESH': '需要刷新',
    },
    'risk': {
        'LOW_RISK': '低风险',
        'LIGHT_OBSERVATION': '轻度观察',
        'MEDIUM_RISK': '中度风险',
        'HIGH_RISK': '高风险',
        'EXTREME_RISK': '极高风险',
    },
    'evidence': {
        'E0': '无有效证据',
        'E1': '单点弱证据',
        'E2': '多字段弱关联',
        'E3': '当前代币内强证据',
        'E4': '当前代币内强证据加同源关系',
        'E5': '跨代币复现加同源回流盈利稳定',
    },
    'tracking': {
        'A0': '不追踪',
        'A1': '弱观察',
        'A2': '普通观察',
        'A3': '重点跟踪',
        'A4': '核心监控',
    },
    'action': {
        'IGNORE': '忽略',
        'WATCH': '观察',
        'TRACK': '跟踪',
        'TRACK_KEY': '重点跟踪',
        'HIGH_RISK_MONITOR': '高风险监控',
        'WRITE_HISTORY': '写入历史库',
        'GENERATE_GMGN_NOTE': '生成 GMGN 备注',
        'ENTER_NEXT_GATE': '进入后续门禁',
        'PAUSE_FOR_REFRESH': '暂停等待刷新',
        'BLOCK_TRADE_FLOW': '阻断进入交易流程',
    },
    'failure': {
        'WALLET_STRUCTURE_FAILURE': '钱包结构失效',
        'EARLY_WALLET_EXIT': '早期钱包退出',
        'SAME_SOURCE_SYNC_EXIT': '同源组同步退出',
        'CHIP_TO_COUNTERPARTY': '筹码转向对手盘',
        'COUNTERPARTY_PRESSURE_HIGH': '对手盘压力过高',
        'TIME_EVIDENCE_EXPIRED': '时间证据过期',
        'WALLET_SNAPSHOT_EXPIRED': '钱包快照过期',
        'QUOTE_EXPIRED': 'quote 过期',
        'PATTERN_INVALID': '盘型失效',
        'LIQUIDITY_INSUFFICIENT': '流动性不足',
        'SECURITY_SCAN_FAILED': '安全扫描未通过',
        'STOP_LOSS_TRIGGERED': '止损触发',
        'TIME_STOP_LOSS': '时间止损',
        'STRATEGY_MISMATCH': '策略不匹配',
    },
}

def zh(category: str, code: str, default: str = '') -> str:
    return CHINESE_JUDGEMENT.get(category, {}).get(code, default or code)
