#!/usr/bin/env python3
from pathlib import Path
import json, csv, sys
base=Path('/root/sikk-gmgn')
required = [
"modules/source_wallet_bot/package_file_passport.json",
"modules/source_wallet_bot/package_file_passport.md",
"modules/source_wallet_bot/legacy_mapping.md",
"modules/source_wallet_bot/old_system_inventory.json",
"modules/source_wallet_bot/codebase_inspection_report.md",
"modules/source_wallet_bot/kanban_task_board.md",
"modules/source_wallet_bot/gmgn_to_sikk_field_mapping.csv",
"modules/source_wallet_bot/field_dictionary.csv",
"modules/source_wallet_bot/missing_fields_report.md",
"modules/source_wallet_bot/source_registry.md",
"modules/source_wallet_bot/source_registry_schema.json",
"modules/source_wallet_bot/source_reliability_matrix.csv",
"modules/source_wallet_bot/wallet_trade_contract.md",
"modules/source_wallet_bot/source_manifest_contract.md",
"modules/source_wallet_bot/wallet_intelligence_contracts.md",
"modules/source_wallet_bot/source_and_group_models.md",
"modules/source_wallet_bot/distribution_recovery_whale_rules.md",
"modules/source_wallet_bot/evidence_note_rules.md",
"modules/source_wallet_bot/bot2_handoff_contract.md",
"modules/source_wallet_bot/final_module_package.md",
"data/source_wallet_bot/source_bot_schema_plan.json",
"data/source_wallet_bot/audit/kanban_task_board.json",
"data/source_wallet_bot/wallet_trade_normalized.json",
"data/source_wallet_bot/same_source_evidence_normalized.json",
"data/source_wallet_bot/backflow_paths_normalized.json",
"data/source_wallet_bot/bot2_handoff_packet.json",
"data/source_wallet_bot/schemas/wallet_trade_normalized.schema.json",
"data/source_wallet_bot/schemas/wallet_profile_normalized.schema.json",
"data/source_wallet_bot/schemas/funding_flow_normalized.schema.json",
"data/source_wallet_bot/schemas/token_source_normalized.schema.json",
"data/source_wallet_bot/schemas/token_transfer_normalized.schema.json",
"data/source_wallet_bot/schemas/same_source_evidence_normalized.schema.json",
"data/source_wallet_bot/schemas/backflow_paths_normalized.schema.json",
"data/source_wallet_bot/schemas/wallet_intelligence_decision.schema.json",
"data/source_wallet_bot/schemas/bot2_handoff_packet.schema.json",
"research_loop/checkpoints/round_0_import_safety.md",
"research_loop/checkpoints/round_1_package_passport.md",
"research_loop/checkpoints/round_2_source_registry.md",
"research_loop/checkpoints/round_2_old_system_audit.md",
"research_loop/checkpoints/round_3_field_mapping.md",
"research_loop/checkpoints/round_4_wallet_contracts.md",
"research_loop/checkpoints/round_5_source_and_group_models.md",
"research_loop/checkpoints/round_6_distribution_recovery_whale.md",
"research_loop/checkpoints/round_7_evidence_note_rules.md",
"research_loop/checkpoints/round_8_handoff_contract.md",
"research_loop/checkpoints/round_9_final_module_package.md",
"research_loop/checkpoints/final_acceptance.md",
]
missing=[p for p in required if not (base/p).exists()]
if missing:
    print('MISSING')
    print('\\n'.join(missing))
    raise SystemExit(1)
# CSV required fields
with open(base/'modules/source_wallet_bot/gmgn_to_sikk_field_mapping.csv', newline='', encoding='utf-8') as f:
    fields=set(row.get('sikk_field','') for row in csv.DictReader(f))
for field in ['token_address', 'wallet_address', 'first_buy_time', 'last_buy_time', 'last_sell_time', 'buy_count', 'sell_count', 'buy_amount_sol', 'buy_amount_usd', 'buy_token_amount', 'sell_amount_sol', 'sell_amount_usd', 'sell_token_amount', 'avg_buy_price', 'avg_sell_price', 'current_balance', 'sold_pct', 'remaining_pct', 'realized_profit', 'unrealized_profit', 'total_profit', 'pnl_multiple', 'holding_duration_seconds', 'is_full_exit', 'is_partial_exit']:
    if field not in fields:
        print('MISSING_FIELD_MAPPING', field)
        raise SystemExit(1)
# JSON parse schemas
for p in (base/'data/source_wallet_bot/schemas').glob('*.json'):
    json.loads(p.read_text(encoding='utf-8'))
# forbidden language scan in source bot docs/checkpoints generated by this module
forbidden=['确定庄家', '一定是庄家', '百分百内幕', '绝对老鼠仓']
scan_roots=[base/'modules/source_wallet_bot', base/'research_loop/checkpoints']
for root in scan_roots:
    for p in root.glob('*.md'):
        text=p.read_text(encoding='utf-8', errors='ignore')
        # allow occurrence only inside explicit Forbidden language sections
        for word in forbidden:
            if word in text and 'Forbidden language' not in text and '禁止语言' not in text and '禁止交接字段' not in text:
                print('FORBIDDEN_LANGUAGE', p, word)
                raise SystemExit(1)
print('SOURCE_WALLET_BOT_ACCEPTANCE_PASS')
