def build_policy_rules(classification):
    rules=[]
    for c in classification.get("classified_candidates",[]):
        src=c.get("source_candidate",{})
        cid=c["candidate_id"]
        statement=src.get("problem_statement") or src.get("rule_statement") or src.get("proposed_change") or cid
        rules.append({"policy_rule_id":f"{c['policy_domain']}_{cid}_v1","policy_domain":c["policy_domain"],"rule_type":c.get("recommended_policy_level","RULE"),"rule_statement":statement,"applies_to":["G00","O00","A00","U00"],"violation_effect":"STATUS_INVALID","required_recovery":"route_to_U00_or_G00","source_candidate_id":cid,"evidence_refs":src.get("evidence_refs",[]),"version":"1.0.0","status":"PENDING_ACTIVE"})
    return {"policy_rules":rules}
def static_policies():
    forbidden={"policy_id":"forbidden_action_policy_v1","policy_domain":"forbidden_action_policy","version":"1.0.0","rules":[{"rule_id":f"forbid_{a}","action":a,"policy_level":"HARD_FORBIDDEN","applies_to":"ALL_CONTROLLERS","violation_effect":"BLOCK_IMMEDIATELY","allowed_exception":False} for a in ["live_runtime","wallet_signing","auto_deploy","production_trading","execute_real_order"]]}
    status={"policy_id":"status_code_policy_v1","version":"1.0.0","status_rules":[{"status_code":"READY_WITH_GAPS","definition":"可继续下游处理，但必须携带 gap_refs，不允许改写为 ACCEPTED。","required_fields":["gap_refs","allowed_next_actions","forbidden_next_actions"],"forbidden_equivalent_statuses":["ACCEPTED","PIPELINE_ACCEPTED","SYSTEM_FULLY_IMPLEMENTED"]},{"status_code":"POLICY_CANDIDATE","definition":"治理候选规则，未经过冲突检查与激活验收。","forbidden_equivalent_statuses":["POLICY_ACTIVE","GOVERNANCE_ENFORCED"]},{"status_code":"QUEUE_READY_WITH_GAPS","definition":"下游队列已生成，但下游任务尚未完成。","forbidden_equivalent_statuses":["DOWNSTREAM_EXECUTED","ITEM_COMPLETED"]},{"status_code":"UPGRADE_QUEUE_READY_WITH_GAPS","definition":"升级队列已生成，但升级尚未应用。","forbidden_equivalent_statuses":["UPGRADE_APPLIED","IMPLEMENTED"]}]}
    evidence={"policy_id":"evidence_policy_v1","version":"1.0.0","evidence_rules":[{"rule_id":"test_plan_not_tested","claim":"TESTED","minimum_required_evidence":["test_command","exit_code","stdout_path","stderr_path","passed_count","failed_count"],"invalid_evidence":["test_plan","manual_claim","expected_output_only"],"missing_policy":"DOWNGRADE_TO_TEST_PLANNED_ONLY"},{"rule_id":"binding_plan_not_runner_bound","claim":"RUNNER_BOUND","minimum_required_evidence":["command_contract","safe_dry_run_evidence","exit_code","stdout_path","stderr_path"],"invalid_evidence":["binding_plan","command_plan","manual_claim"],"missing_policy":"DOWNGRADE_TO_BINDING_PLANNED_ONLY"},{"rule_id":"policy_candidate_not_active","claim":"POLICY_ACTIVE","minimum_required_evidence":["policy_conflict_report","active_policy_bundle","governance_registry","g00_acceptance_result"],"invalid_evidence":["governance_candidate","pending_policy_bundle","manual_claim"],"missing_policy":"DOWNGRADE_TO_POLICY_PENDING"}]}
    gap={"policy_id":"gap_policy_v1","version":"1.0.0","gap_rules":[{"gap_type":"policy_not_active","default_level":"HIGH_GAP","must_propagate":True,"cannot_be_deleted":True,"required_route":"G00"},{"gap_type":"run_document_not_validated","default_level":"HIGH_GAP","must_propagate":True,"required_route":"O00"},{"gap_type":"upgrade_items_not_applied","default_level":"HIGH_GAP","must_propagate":True,"required_route":"U00"}]}
    runner={"policy_id":"runner_safety_policy_v1","version":"1.0.0","runner_rules":[{"runner_mode":"SAFE_DRY_RUN","allowed":True,"requirements":["safe_mode=true","dry_run_evidence","exit_code"]},{"runner_mode":"PAPER_RUNTIME","allowed":False,"activation_requirement":["explicit_human_confirmation","A00_ACCEPTED_OR_APPROVED_READY_WITH_GAPS","G00_policy_loaded"]},{"runner_mode":"LIVE_RUNTIME","allowed":False,"policy_level":"HARD_FORBIDDEN"}]}
    human={"policy_id":"human_confirmation_policy_v1","version":"1.0.0","confirmation_rules":[{"action_type":"policy_activation","requires_confirmation":False,"requires_acceptance_evidence":True},{"action_type":"paper_runtime_enable","requires_confirmation":True,"without_confirmation":"BLOCK_ACTION"},{"action_type":"scheduler_enable","requires_confirmation":True,"without_confirmation":"BLOCK_ACTION"},{"action_type":"data_deletion","requires_confirmation":True,"without_confirmation":"BLOCK_ACTION"}]}
    prod={"policy_id":"production_risk_policy_v1","version":"1.0.0","risk_rules":[{"risk_type":"LIVE_RUNTIME_RISK","default_action":"HARD_BLOCK","allowed_exception":False},{"risk_type":"WALLET_SIGNING_RISK","default_action":"HARD_BLOCK","allowed_exception":False},{"risk_type":"AUTO_DEPLOY_RISK","default_action":"HARD_BLOCK","allowed_exception":False},{"risk_type":"PRODUCTION_TRADING_RISK","default_action":"HARD_BLOCK","allowed_exception":False}]}
    return forbidden,status,evidence,gap,runner,human,prod
