#!/usr/bin/env python3
"""Generate SIKK Stable Trader OS × HER professional baseline v1.0.
Additive only: creates/overwrites the dedicated baseline docs/contracts/reports generated by this task; does not delete or move legacy runtime files.
"""
from pathlib import Path
import json
from datetime import datetime, timezone

ROOT = Path('/root/sikk-gmgn')
NOW = datetime.now(timezone.utc).isoformat()
GOAL = "SIKK Stable Trader OS 不是寻找机会系统，而是从所有看起来像机会的结构中，连续剔除低质量、错误场景、假成交、派发风险、疲劳拖延和错误位置，只保留极少数 A+P1 且证据链未被否决的样本。"

phases = [
    (0, 'system_constitution', '系统宪法层', '固定总目标、禁止事项、目录标准、HER 专业化角色边界', 'system_constitution.md'),
    (1, 'data_fact', '数据事实层', '标准化 GMGN / 链上 / K 线 / quote 数据并输出数据质量状态', 'data_quality_summary.json'),
    (2, 'wallet_structure', '结构地址层', '识别疑似结构钱包、同源组、回流路径和风险结构角色', 'wallet_structure_decision.json'),
    (3, 'chip_control', '筹码控制层', '判断结构侧筹码是否仍有控制权、是否迁移/松动/派发', 'chip_control_summary.json'),
    (4, 'scenario_recognition', '多模型场景识别层', '识别市场生命周期、成交真实性、钱包配合和主场景裁决', 'primary_scenario.json'),
    (5, 'structure_position', '结构位置确认层', '判断 AVWAP / POC / Failure Test / 疲劳否定是否完成', 'structure_position_decision.json'),
    (6, 'strategy_gate', '策略过滤层', '判断是否达到 A+P1 且未被证据链否决', 'strategy_gate_decision.json'),
    (7, 'execution_risk', '执行风控层', '检查 quote、安全、滑点、流动性与纸面交易资格；默认 paper-only', 'paper_trade_decision.json'),
    (8, 'review_learning', '复盘学习层', '沉淀失败归因、历史样本、规则修正候选', 'failure_attribution.jsonl'),
    (9, 'system_upgrade', '系统自我升级层', '阈值校准、规则版本、模型淘汰、系统升级包', 'rule_update_package.json'),
]

stage_files = [
    ('00_stage_goal.md', '阶段目标'), ('01_phase_position.md', '阶段位置'), ('02_layer_step_map.md', '层与步骤'),
    ('03_input_contract.md', '输入合约'), ('04_output_contract.md', '输出合约'), ('05_required_fields.md', '字段要求'),
    ('06_reasoning_rules.md', '正向规则'), ('07_counter_evidence_rules.md', '反证规则'), ('08_hard_negative_rules.md', '硬否决规则'),
    ('09_status_codes.md', '状态码'), ('10_handoff_rules.md', '交接规则'), ('11_acceptance.md', '验收标准'),
    ('12_gaps.md', '缺口'), ('13_implementation_plan.md', '实现计划'), ('14_test_plan.md', '测试计划'), ('15_audit_report.md', '审计报告')
]

status_by_phase = {
    0: ['CONSTITUTION_READY','CONSTITUTION_GAP','CONSTITUTION_BLOCK'],
    1: ['DATA_OK','DATA_WEAK','DATA_INVALID'],
    2: ['WALLET_SUPPORT','WALLET_PAUSE','WALLET_BLOCK'],
    3: ['CONTROL_RETAINED','CONTROL_WEAKENING','ACTIVE_DISTRIBUTION','STRUCTURE_COLLAPSE'],
    4: ['SCENARIO_ALLOW','SCENARIO_PAUSE','SCENARIO_BLOCK'],
    5: ['COMPLETION_PASS','COMPLETION_WAIT','COMPLETION_FAIL','FATIGUE_BLOCK'],
    6: ['STRATEGY_BLOCK','STRATEGY_PAUSE','PAPER_READY','READY_FOR_CONFIRMATION'],
    7: ['EXECUTION_BLOCK','PAPER_EXECUTED','REVIEW_ONLY'],
    8: ['RULE_UPDATE_REQUIRED','MODEL_RECALIBRATION_REQUIRED','REVIEW_ARCHIVED'],
    9: ['UPGRADE_PROPOSED','UPGRADE_REJECTED','UPGRADE_ACCEPTED','MODEL_RETIRED'],
}

def phase_dir(num, slug):
    long = {
        0:'phase_00_system_constitution',1:'phase_01_data_fact_layer',2:'phase_02_wallet_structure_layer',3:'phase_03_chip_control_layer',4:'phase_04_scenario_recognition_layer',5:'phase_05_structure_position_layer',6:'phase_06_strategy_gate_layer',7:'phase_07_execution_risk_layer',8:'phase_08_review_learning_layer',9:'phase_09_system_upgrade_layer'
    }
    return ROOT / 'research_loop' / long[num]

def next_phase(num):
    return phases[num+1] if num < 9 else None

def input_from(num):
    if num == 0: return ['用户目标定义文档', 'AGENTS.md', 'docs/system_directory_constitution.md']
    prev = phases[num-1]
    return [f"research_loop/{phase_dir(prev[0],prev[1]).name}/{prev[4]}", f"reports/system_audit/phase_handoff_flow.md"]

def layer_map(num):
    maps = {
        0:['0.1 总目标冻结','0.2 禁止事项与边界','0.3 目录宪法','0.4 HER 角色固定','0.5 审计入口'],
        1:['1.1 Source 输入识别','1.2 字段标准化','1.3 数据质量评分','1.4 缺失标记','1.5 下游事实包'],
        2:['2.1 早期钱包窗口','2.2 结构角色候选','2.3 同源/回流/分发路径','2.4 正反证裁决','2.5 钱包决策交接'],
        3:['3.1 Top Holder 变化','3.2 控制侧余额','3.3 筹码迁移','3.4 派发/坍塌反证','3.5 控制权状态'],
        4:['4.1 市场生命周期','4.2 K线结构','4.3 成交真实性','4.4 钱包结构配合','4.5 筹码迁移状态','4.6 场景候选打分','4.7 反证与硬否决','4.8 主场景裁决','4.9 下游交接'],
        5:['5.1 AVWAP 相对位置','5.2 POC/成交密集区','5.3 Failure Test','5.4 疲劳拖延识别','5.5 Completion 裁决'],
        6:['6.1 A级结构检查','6.2 P1优先级检查','6.3 全链路反证扫描','6.4 策略门禁裁决','6.5 纸面交接'],
        7:['7.1 quote 有效性','7.2 安全/权限检查','7.3 滑点/流动性','7.4 纸面执行记录','7.5 Review-only 交接'],
        8:['8.1 结果采集','8.2 失败归因','8.3 规则回灌候选','8.4 历史样本沉淀','8.5 升级包交接'],
        9:['9.1 阈值校准','9.2 规则版本','9.3 模型淘汰','9.4 Telegram 展示更新','9.5 审计发布'],
    }
    return maps[num]

def common_content(num, slug, name, goal, output, title):
    nxt = next_phase(num)
    downstream = f"第 {nxt[0]} 阶段：{nxt[2]}" if nxt else '终点：进入人工审计/下一版本循环'
    inputs = input_from(num)
    statuses = status_by_phase[num]
    layers = layer_map(num)
    return f"""# {name} - {title}

生成时间：{NOW}
版本：SIKK Stable Trader OS × HER 专业化基线 v1.0
生成性质：系统推导；非空模板；用于后续代码实现、合约检查和状态流转。

## 总目标约束
{GOAL}

## 本阶段目标
{goal}

## 本阶段位置
- 阶段编号：{num}
- 阶段名称：{name}
- 核心输出：`{output}`
- 下游读取者：{downstream}

## 输入文件
""" + ''.join([f"- `{x}`\n" for x in inputs]) + f"""
## 必需字段
- `token_address`：代币地址；缺失写 `missing`。
- `run_id`：运行 ID；缺失由状态机生成并标记 `系统推导`。
- `source_files`：本阶段实际读取文件列表。
- `data_quality_status`：来自上游或本阶段校验。
- `positive_evidence`：支持进入下一阶段的证据数组。
- `negative_evidence`：削弱判断的证据数组。
- `counter_evidence`：直接反驳候选判断的证据数组。
- `hard_negative_trigger`：一票否决触发器；无触发时为空数组。
- `status_code`：必须属于本阶段状态码。

## 阶段内部层次与步骤
""" + ''.join([f"### {x}\n- 目标：围绕 `{name}` 的阶段目标执行可审计判断。\n- 输入：上游合约文件 + 本层所需字段。\n- 处理：先字段校验，再正向证据，再反证，再硬否决。\n- 输出：本层结论、证据、反证、状态片段。\n- 验收：不能只有结论；必须有证据链和缺口标记。\n\n" for x in layers]) + f"""
## 正向判断规则
- 只有当本阶段关键字段存在且证据链完整时，才允许输出支持类状态。
- 支持证据必须引用字段来源，不能使用“感觉不错/可能能买”等自然语言替代状态码。
- 自动补全内容必须标记 `系统推导`。

## 反证规则
- 每个支持判断必须同时扫描 `negative_evidence` 与 `counter_evidence`。
- 如果反证强于正证，状态必须降级为 PAUSE / BLOCK / WAIT / REVIEW_ONLY 等对应状态。
- 任何无法验证的数据来源必须写入 `gaps.md`，不得静默通过。

## 硬否决规则
- 安全/权限/合约风险未通过：硬否决。
- 假成交、派发、结构坍塌、疲劳拖延、错误位置任一达到硬触发：硬否决。
- 状态码不在码表内：硬否决本阶段交接。
- 输出无人读取或字段无来源：硬否决专业化验收。

## 状态码
""" + ''.join([f"- `{s}`\n" for s in statuses]) + f"""
## 输出文件与字段
- 输出文件：`{output}`
- 最小字段：`token_address`, `run_id`, `phase`, `status_code`, `positive_evidence`, `negative_evidence`, `counter_evidence`, `hard_negative_trigger`, `confidence_level`, `missing_fields`, `source_files`, `handoff_to`。

## 下游交接
- 交接对象：{downstream}
- 交接方式：下游只读取本阶段 `output_contract` 中声明的字段。
- 失败处理：状态为 BLOCK/FAIL/INVALID 时，下游不得升级为交易候选，只能进入复盘或缺口修复。

## 验收标准
- 文件真实存在且非空。
- 每个判断有正证与反证。
- 每个缺失字段标记 `missing`。
- 状态码可被全局状态表识别。
- 输出文件有下游读取者。
- 旧数据不删除、不移动；仅新增标准基线文件。

## 当前缺口
- 真实 GMGN/OKX/RPC 字段绑定需要在后续实现中逐项接入。
- 阈值尚未全部量化；先以规则占位并标记 `系统推导`。
- 需要后续测试把合约与实际 pipeline 连接。
"""

def write(p, content):
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding='utf-8')

# top directories and README
base_dirs = ['docs','contracts','research_loop','schemas','src','data','tests','reports','tools','telegram_panel']
for d in base_dirs:
    path = ROOT/d
    path.mkdir(parents=True, exist_ok=True)
    readme = path/'README.md'
    if not readme.exists():
        write(readme, f"# {d}\n\nSIKK Stable Trader OS 专业化基线目录。用途：承载 HER 阶段化系统工程产物。\n\n边界：不删除旧数据，不移动旧运行目录；新增文件必须有读取者、合约或审计用途。\n")

# docs subdirs
for d in ['00_system_goal','01_stage_definitions','02_phase_layer_step_maps','03_reasoning_rules','04_hard_negative_rules','05_status_codes','06_directory_constitution','07_telegram_panel_design','08_review_learning_rules','09_system_upgrade_rules']:
    (ROOT/'docs'/d).mkdir(parents=True, exist_ok=True)
    rp=ROOT/'docs'/d/'README.md'
    if not rp.exists(): write(rp, f"# {d}\n\nHER 专业化系统基线文档目录。\n")

# phase dirs in contracts/schemas/src/tests too
for num, slug, name, goal, output in phases:
    for top in ['contracts','src','tests']:
        pd = ROOT/top/f"phase_{num:02d}_{slug}"
        pd.mkdir(parents=True, exist_ok=True)
        r = pd/'README.md'
        if not r.exists(): write(r, f"# {name}\n\n目标：{goal}\n核心输出：`{output}`\n")
    sd = ROOT/'schemas'/f"phase_{num:02d}_{slug}"
    sd.mkdir(parents=True, exist_ok=True)
    if not (sd/'README.md').exists(): write(sd/'README.md', f"# {name} schemas\n\n状态码：{', '.join(status_by_phase[num])}\n")

# data subdirs from spec
for d in ['legacy_runtime_keep_in_place','source_wallet_bot','intel_bot','strategy_gate','execution_risk','review_learning','shared_handoff','telegram_runtime']:
    (ROOT/'data'/d).mkdir(parents=True, exist_ok=True)

# reports/tools/telegram subdirs
for d in ['daily','token','wallet','chip','scenario','strategy','execution','failure_attribution','system_audit']:
    (ROOT/'reports'/d).mkdir(parents=True, exist_ok=True)
for d in ['audit','migration','validation','replay','contract_check','status_check']:
    (ROOT/'tools'/d).mkdir(parents=True, exist_ok=True)
for d in ['commands','views','callbacks','state_router','token_detail_pages','wallet_detail_pages','scenario_detail_pages','paper_position_pages','review_pages']:
    (ROOT/'telegram_panel'/d).mkdir(parents=True, exist_ok=True)

# stage files
for num, slug, name, goal, output in phases:
    pd = phase_dir(num, slug)
    pd.mkdir(parents=True, exist_ok=True)
    write(pd/'README.md', f"# {name}\n\n阶段目标：{goal}\n核心输出：`{output}`\n状态码：{', '.join(status_by_phase[num])}\n")
    for fname, title in stage_files:
        write(pd/fname, common_content(num, slug, name, goal, output, title))
    # contracts and schema json
    contract = {
        'phase': num, 'name': name, 'goal': goal, 'output_file': output,
        'required_fields': ['token_address','run_id','phase','status_code','positive_evidence','negative_evidence','counter_evidence','hard_negative_trigger','confidence_level','missing_fields','source_files','handoff_to'],
        'allowed_status_codes': status_by_phase[num], 'missing_policy': '缺失字段必须写 missing；自动推导写 系统推导', 'downstream': next_phase(num)[2] if next_phase(num) else 'audit_or_next_version'
    }
    write(ROOT/'contracts'/f"phase_{num:02d}_{slug}"/'input_contract.json', json.dumps(contract, ensure_ascii=False, indent=2))
    write(ROOT/'contracts'/f"phase_{num:02d}_{slug}"/'output_contract.json', json.dumps(contract, ensure_ascii=False, indent=2))
    schema = {'$schema':'https://json-schema.org/draft/2020-12/schema','title':name,'type':'object','required':contract['required_fields'],'properties':{k:{'type':['string','array','object','number','boolean','null']} for k in contract['required_fields']}}
    write(ROOT/'schemas'/f"phase_{num:02d}_{slug}"/'schema.json', json.dumps(schema, ensure_ascii=False, indent=2))

# total docs
stage_table = '\n'.join([f"- 第 {n} 阶段：{name}｜目标：{goal}｜核心输出：`{out}`｜状态码：{', '.join(status_by_phase[n])}" for n,slug,name,goal,out in phases])
write(ROOT/'docs/00_system_goal/sikk_stable_trader_os_goal.md', f"# SIKK Stable Trader OS 总目标\n\n{GOAL}\n\n## HER 角色\nHER 不是聊天助手；HER 是 SIKK 系统的阶段生成器、合约检查器、状态流转器、审计执行器。\n")
write(ROOT/'docs/01_stage_definitions/full_stage_map.md', f"# 10 阶段全图\n\n{stage_table}\n")
write(ROOT/'docs/02_phase_layer_step_maps/full_phase_layer_step_map.md', '# 全阶段层内步骤图\n\n' + '\n'.join([f"## 第 {n} 阶段 {name}\n" + '\n'.join([f"- {x}" for x in layer_map(n)]) for n,slug,name,goal,out in phases]))
write(ROOT/'docs/03_reasoning_rules/evidence_and_counter_evidence_rules.md', f"# 正向证据与反证规则\n\n{GOAL}\n\n每个阶段必须输出 positive_evidence、negative_evidence、counter_evidence、hard_negative_trigger、invalidation_condition、confidence_level。支持判断必须可被反证否决。\n")
write(ROOT/'docs/03_reasoning_rules/phase_auto_expander_protocol.md', "# HER 阶段自动展开协议\n\n当用户只提供：总目标、当前阶段名称、当前阶段目标、阶段分层方向，HER 必须自动推导：输入、输出、字段、步骤、正向规则、反证规则、硬否决规则、状态码、验收、缺口、下游交接。\n\n## 强制标记\n- 自动补全：`系统推导`\n- 缺失字段：`missing`\n- 不确定内容：写入 `gaps.md`\n\n## 执行顺序\n读取总目标 → 阶段目标 → 阶段分类 → 层内步骤 → 输入合约 → 输出合约 → 字段 → 正证/反证 → 硬否决 → 状态码 → 验收 → 交接 → 审计。\n")
write(ROOT/'docs/04_hard_negative_rules/global_hard_negative_rules.md', '# 全局硬否决规则\n\n- 合约/权限/安全风险未过。\n- 假成交证据成立。\n- ACTIVE_DISTRIBUTION / STRUCTURE_COLLAPSE 成立。\n- 疲劳拖延或错误位置触发。\n- 字段无来源、状态码不可读、输出无人读取。\n')
all_status='\n'.join([f"## 第 {n} 阶段 {name}\n"+'\n'.join([f"- `{s}`" for s in status_by_phase[n]]) for n,slug,name,goal,out in phases])
write(ROOT/'docs/05_status_codes/global_status_code_table.md', '# 全局状态码表\n\n' + all_status)
write(ROOT/'docs/06_directory_constitution/directory_constitution.md', '# 目录宪法\n\n新增专业化基线写入 docs/contracts/research_loop/schemas/src/data/tests/reports/tools/telegram_panel。旧数据不删除、不移动。每个文件必须有读取者、合约或审计用途。\n')
write(ROOT/'docs/07_telegram_panel_design/telegram_panel_professional_design.md', '# Telegram 面板专业化设计\n\n面板只展示阶段状态、证据等级、风险等级、反证、硬否决、下一步交接；禁止展示“确定庄家”或把指标当买点。\n')
write(ROOT/'docs/08_review_learning_rules/review_learning_rules.md', '# 复盘学习规则\n\n失败必须归因到阶段、字段、规则、反证或硬否决。复盘输出进入 failure_attribution.jsonl，并作为 rule_update_package.json 候选输入。\n')
write(ROOT/'docs/09_system_upgrade_rules/system_upgrade_rules.md', '# 系统升级规则\n\n升级必须基于历史样本、纸面验证、失败归因和审计报告。规则更新必须版本化，模型可淘汰，不能因单样本过拟合。\n')

# audit reports
tree_lines=[]
for p in sorted([x for x in ROOT.rglob('*') if any(str(x).startswith(str(ROOT/d)) for d in base_dirs)]):
    rel=p.relative_to(ROOT)
    if len(rel.parts)<=3 and p.is_dir(): tree_lines.append(f"- `{rel}/`")
write(ROOT/'reports/system_audit/directory_tree.md', '# 目录树审计\n\n'+'\n'.join(tree_lines[:500]))
write(ROOT/'reports/system_audit/phase_goal_table.md', '# 阶段目标表\n\n'+stage_table)
write(ROOT/'reports/system_audit/phase_layer_step_map.md', (ROOT/'docs/02_phase_layer_step_maps/full_phase_layer_step_map.md').read_text(encoding='utf-8'))
flow='\n'.join([f"- 第 {n} 阶段 `{out}` → {next_phase(n)[2] if next_phase(n) else '人工审计/下一版本循环'}" for n,slug,name,goal,out in phases])
write(ROOT/'reports/system_audit/phase_handoff_flow.md', '# 阶段交接流\n\n'+flow)
write(ROOT/'reports/system_audit/status_code_table.md', (ROOT/'docs/05_status_codes/global_status_code_table.md').read_text(encoding='utf-8'))
write(ROOT/'reports/system_audit/missing_gap_register.md', '# 缺口登记\n\n- 真实代码实现：多数阶段仍为合约/规则/审计基线，后续需接入 pipeline。\n- 真实字段来源：GMGN/OKX/RPC/K线字段需逐项绑定。\n- 阈值量化：疲劳、假成交、派发风险、A+P1 阈值需样本回放校准。\n- 状态机消费：需要后续实现 candidate_state_contract.json 与读取器。\n')
created_dirs_list = ''.join([f'- `{d}/`' + chr(10) for d in base_dirs])
accept = f"""# professional_baseline_acceptance_report

生成时间：{NOW}

## 总目标
{GOAL}

## 已创建/确认核心目录
{created_dirs_list}

## 已创建阶段文件
- 10 个阶段目录位于 `research_loop/phase_00...phase_09.../`。
- 每个阶段均包含 16 个标准文件：{', '.join([x[0] for x in stage_files])}。
- 每个阶段均生成 `contracts/phase_xx_*/input_contract.json`、`output_contract.json` 和 `schemas/phase_xx_*/schema.json`。

## 每阶段核心目标与输出
{stage_table}

## 下游交接
{flow}

## 当前仍缺真实代码实现
- 阶段执行器、状态机读取器、合约校验 CLI、Telegram 页面跳转、回放校准器仍需下一轮实现。
- 当前完成的是专业化系统工程基线，不声称已完成交易判断代码。

## 系统推导内容
- 阶段内部层次、字段、状态码、正反证、硬否决、验收、交接均按用户目标进行 `系统推导`。

## missing 字段
- 真实 GMGN/OKX/RPC/K线字段绑定尚为 `missing`，已登记在 `missing_gap_register.md`。

## 尚未量化规则
- 假成交阈值、疲劳拖延阈值、派发风险阈值、A+P1 评分阈值、AVWAP/POC/Failure Test 完成阈值。

## 下一轮建议
优先从 `phase_00_system_constitution`、`phase_01_data_fact`、`phase_02_wallet_structure`、`phase_04_scenario_recognition`、`phase_05_structure_position` 开始实现可运行校验器。\n"""
write(ROOT/'reports/system_audit/professional_baseline_acceptance_report.md', accept)
print('generated', ROOT/'reports/system_audit/professional_baseline_acceptance_report.md')
